[profile.default]
solc_version = '0.8.25'
evm_version = "cancun"
optimizer_runs = 800
via_ir = false
ffi = true
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }